<?php
$page = [
    'home' => 'view/home.php',
    'error' => "view/error.php",
    'cart' => 'view/cart.php',
    'signup' => 'view/signup.php',
    'about' => 'view/about.php',
    'wheretobuy' => 'view/wheretobuy.php',
    'faq' => 'view/faq.php',
    'addproduct' => 'view/addproduct.php',
    'modifyproduct' => 'view/modifyproduct.php',
    'login' => 'view/login.php',
    'loginadmin' => 'view/loginadmin.php',
    'adminhome' => 'view/adminhome.php',
    'adminmessages' => 'view/adminmessages.php',
    'payment' => 'view/payment.php',
    'paymentsuccessful' => 'view/paymentsuccessful.php',
    'contact' => 'view/contact.php',
    'inbox' => 'view/inbox.php',
    'edit' => 'view/edit.php',
    'editproducts' => 'view/editproducts.php',
    'productsbuyed' => 'view/productsbuyed.php',
    'profile' => 'view/profile.php',
    'history' => 'view/history.php',
    'userinbox' => 'view/userinbox.php',
    'logout' => 'view/logout.php',
];